services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stageflow-app
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: stageflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stageflow
      MYSQL_USER: stageflow
      MYSQL_PASSWORD: stageflow_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - stageflow_mysql_data:/var/lib/mysql

volumes:
  stageflow_mysql_data: